Fix error when using python 3
Error:
  $ gitconfig
    File "<stdin>", line 15
      print filename
          ^
  SyntaxError: Missing parentheses in call to 'print'. Did you mean print(filename)?
  .git/config not found